# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _eibclient
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


EIB_INVALID_REQUEST = _eibclient.EIB_INVALID_REQUEST
EIB_CONNECTION_INUSE = _eibclient.EIB_CONNECTION_INUSE
EIB_PROCESSING_ERROR = _eibclient.EIB_PROCESSING_ERROR
EIB_CLOSED = _eibclient.EIB_CLOSED
EIB_RESET_CONNECTION = _eibclient.EIB_RESET_CONNECTION
EIB_OPEN_BUSMONITOR = _eibclient.EIB_OPEN_BUSMONITOR
EIB_OPEN_BUSMONITOR_TEXT = _eibclient.EIB_OPEN_BUSMONITOR_TEXT
EIB_OPEN_VBUSMONITOR = _eibclient.EIB_OPEN_VBUSMONITOR
EIB_OPEN_VBUSMONITOR_TEXT = _eibclient.EIB_OPEN_VBUSMONITOR_TEXT
EIB_BUSMONITOR_PACKET = _eibclient.EIB_BUSMONITOR_PACKET
EIB_OPEN_T_CONNECTION = _eibclient.EIB_OPEN_T_CONNECTION
EIB_OPEN_T_INDIVIDUAL = _eibclient.EIB_OPEN_T_INDIVIDUAL
EIB_OPEN_T_GROUP = _eibclient.EIB_OPEN_T_GROUP
EIB_OPEN_T_BROADCAST = _eibclient.EIB_OPEN_T_BROADCAST
EIB_OPEN_T_TPDU = _eibclient.EIB_OPEN_T_TPDU
EIB_APDU_PACKET = _eibclient.EIB_APDU_PACKET
EIB_OPEN_GROUPCON = _eibclient.EIB_OPEN_GROUPCON
EIB_GROUP_PACKET = _eibclient.EIB_GROUP_PACKET
EIB_PROG_MODE = _eibclient.EIB_PROG_MODE
EIB_MASK_VERSION = _eibclient.EIB_MASK_VERSION
EIB_M_INDIVIDUAL_ADDRESS_READ = _eibclient.EIB_M_INDIVIDUAL_ADDRESS_READ
EIB_M_INDIVIDUAL_ADDRESS_WRITE = _eibclient.EIB_M_INDIVIDUAL_ADDRESS_WRITE
EIB_ERROR_ADDR_EXISTS = _eibclient.EIB_ERROR_ADDR_EXISTS
EIB_ERROR_MORE_DEVICE = _eibclient.EIB_ERROR_MORE_DEVICE
EIB_ERROR_TIMEOUT = _eibclient.EIB_ERROR_TIMEOUT
EIB_ERROR_VERIFY = _eibclient.EIB_ERROR_VERIFY
EIB_MC_CONNECTION = _eibclient.EIB_MC_CONNECTION
EIB_MC_READ = _eibclient.EIB_MC_READ
EIB_MC_WRITE = _eibclient.EIB_MC_WRITE
EIB_MC_PROP_READ = _eibclient.EIB_MC_PROP_READ
EIB_MC_PROP_WRITE = _eibclient.EIB_MC_PROP_WRITE
EIB_MC_PEI_TYPE = _eibclient.EIB_MC_PEI_TYPE
EIB_MC_ADC_READ = _eibclient.EIB_MC_ADC_READ
EIB_MC_AUTHORIZE = _eibclient.EIB_MC_AUTHORIZE
EIB_MC_KEY_WRITE = _eibclient.EIB_MC_KEY_WRITE
EIB_MC_MASK_VERSION = _eibclient.EIB_MC_MASK_VERSION
EIB_MC_RESTART = _eibclient.EIB_MC_RESTART
EIB_MC_WRITE_NOVERIFY = _eibclient.EIB_MC_WRITE_NOVERIFY
EIB_MC_PROG_MODE = _eibclient.EIB_MC_PROG_MODE
EIB_MC_PROP_DESC = _eibclient.EIB_MC_PROP_DESC
EIB_MC_PROP_SCAN = _eibclient.EIB_MC_PROP_SCAN
EIB_LOAD_IMAGE = _eibclient.EIB_LOAD_IMAGE
EIB_CACHE_ENABLE = _eibclient.EIB_CACHE_ENABLE
EIB_CACHE_DISABLE = _eibclient.EIB_CACHE_DISABLE
EIB_CACHE_CLEAR = _eibclient.EIB_CACHE_CLEAR
EIB_CACHE_REMOVE = _eibclient.EIB_CACHE_REMOVE
EIB_CACHE_READ = _eibclient.EIB_CACHE_READ
EIB_CACHE_READ_NOWAIT = _eibclient.EIB_CACHE_READ_NOWAIT
EIBSocketURL = _eibclient.EIBSocketURL
EIBSocketLocal = _eibclient.EIBSocketLocal
EIBSocketRemote = _eibclient.EIBSocketRemote
EIBClose = _eibclient.EIBClose
EIBClose_sync = _eibclient.EIBClose_sync
EIBComplete = _eibclient.EIBComplete
EIB_Poll_Complete = _eibclient.EIB_Poll_Complete
EIB_Poll_FD = _eibclient.EIB_Poll_FD
EIBReset = _eibclient.EIBReset
EIBReset_async = _eibclient.EIBReset_async
EIBOpenBusmonitor = _eibclient.EIBOpenBusmonitor
EIBOpenBusmonitor_async = _eibclient.EIBOpenBusmonitor_async
EIBOpenBusmonitorText = _eibclient.EIBOpenBusmonitorText
EIBOpenBusmonitorText_async = _eibclient.EIBOpenBusmonitorText_async
EIBOpenVBusmonitor = _eibclient.EIBOpenVBusmonitor
EIBOpenVBusmonitor_async = _eibclient.EIBOpenVBusmonitor_async
EIBOpenVBusmonitorText = _eibclient.EIBOpenVBusmonitorText
EIBOpenVBusmonitorText_async = _eibclient.EIBOpenVBusmonitorText_async
EIBGetBusmonitorPacket = _eibclient.EIBGetBusmonitorPacket
EIBOpenT_Connection = _eibclient.EIBOpenT_Connection
EIBOpenT_Connection_async = _eibclient.EIBOpenT_Connection_async
EIBOpenT_Individual = _eibclient.EIBOpenT_Individual
EIBOpenT_Individual_async = _eibclient.EIBOpenT_Individual_async
EIBOpenT_Group = _eibclient.EIBOpenT_Group
EIBOpenT_Group_async = _eibclient.EIBOpenT_Group_async
EIBOpenT_Broadcast = _eibclient.EIBOpenT_Broadcast
EIBOpenT_Broadcast_async = _eibclient.EIBOpenT_Broadcast_async
EIBOpenT_TPDU = _eibclient.EIBOpenT_TPDU
EIBOpenT_TPDU_async = _eibclient.EIBOpenT_TPDU_async
EIBSendAPDU = _eibclient.EIBSendAPDU
EIBGetAPDU = _eibclient.EIBGetAPDU
EIBGetAPDU_Src = _eibclient.EIBGetAPDU_Src
EIBSendTPDU = _eibclient.EIBSendTPDU
EIBGetTPDU = _eibclient.EIBGetTPDU
EIBOpen_GroupSocket = _eibclient.EIBOpen_GroupSocket
EIBOpen_GroupSocket_async = _eibclient.EIBOpen_GroupSocket_async
EIBSendGroup = _eibclient.EIBSendGroup
EIBGetGroup_Src = _eibclient.EIBGetGroup_Src
EIB_M_ReadIndividualAddresses = _eibclient.EIB_M_ReadIndividualAddresses
EIB_M_ReadIndividualAddresses_async = _eibclient.EIB_M_ReadIndividualAddresses_async
EIB_M_Progmode_On = _eibclient.EIB_M_Progmode_On
EIB_M_Progmode_On_async = _eibclient.EIB_M_Progmode_On_async
EIB_M_Progmode_Off = _eibclient.EIB_M_Progmode_Off
EIB_M_Progmode_Off_async = _eibclient.EIB_M_Progmode_Off_async
EIB_M_Progmode_Toggle = _eibclient.EIB_M_Progmode_Toggle
EIB_M_Progmode_Toggle_async = _eibclient.EIB_M_Progmode_Toggle_async
EIB_M_Progmode_Status = _eibclient.EIB_M_Progmode_Status
EIB_M_Progmode_Status_async = _eibclient.EIB_M_Progmode_Status_async
EIB_M_GetMaskVersion = _eibclient.EIB_M_GetMaskVersion
EIB_M_GetMaskVersion_async = _eibclient.EIB_M_GetMaskVersion_async
EIB_M_WriteIndividualAddress = _eibclient.EIB_M_WriteIndividualAddress
EIB_M_WriteIndividualAddress_async = _eibclient.EIB_M_WriteIndividualAddress_async
EIB_MC_Connect = _eibclient.EIB_MC_Connect
EIB_MC_Connect_async = _eibclient.EIB_MC_Connect_async
EIB_MC_Read = _eibclient.EIB_MC_Read
EIB_MC_Read_async = _eibclient.EIB_MC_Read_async
EIB_MC_Write = _eibclient.EIB_MC_Write
EIB_MC_Write_async = _eibclient.EIB_MC_Write_async
EIB_MC_Progmode_On = _eibclient.EIB_MC_Progmode_On
EIB_MC_Progmode_On_async = _eibclient.EIB_MC_Progmode_On_async
EIB_MC_Progmode_Off = _eibclient.EIB_MC_Progmode_Off
EIB_MC_Progmode_Off_async = _eibclient.EIB_MC_Progmode_Off_async
EIB_MC_Progmode_Toggle = _eibclient.EIB_MC_Progmode_Toggle
EIB_MC_Progmode_Toggle_async = _eibclient.EIB_MC_Progmode_Toggle_async
EIB_MC_Progmode_Status = _eibclient.EIB_MC_Progmode_Status
EIB_MC_Progmode_Status_async = _eibclient.EIB_MC_Progmode_Status_async
EIB_MC_GetMaskVersion = _eibclient.EIB_MC_GetMaskVersion
EIB_MC_GetMaskVersion_async = _eibclient.EIB_MC_GetMaskVersion_async
EIB_MC_PropertyRead = _eibclient.EIB_MC_PropertyRead
EIB_MC_PropertyRead_async = _eibclient.EIB_MC_PropertyRead_async
EIB_MC_PropertyWrite = _eibclient.EIB_MC_PropertyWrite
EIB_MC_PropertyWrite_async = _eibclient.EIB_MC_PropertyWrite_async
EIB_MC_PropertyDesc = _eibclient.EIB_MC_PropertyDesc
EIB_MC_PropertyDesc_async = _eibclient.EIB_MC_PropertyDesc_async
EIB_MC_PropertyScan = _eibclient.EIB_MC_PropertyScan
EIB_MC_PropertyScan_async = _eibclient.EIB_MC_PropertyScan_async
EIB_MC_GetPEIType = _eibclient.EIB_MC_GetPEIType
EIB_MC_GetPEIType_async = _eibclient.EIB_MC_GetPEIType_async
EIB_MC_ReadADC = _eibclient.EIB_MC_ReadADC
EIB_MC_ReadADC_async = _eibclient.EIB_MC_ReadADC_async
EIB_MC_Authorize = _eibclient.EIB_MC_Authorize
EIB_MC_Authorize_async = _eibclient.EIB_MC_Authorize_async
EIB_MC_SetKey = _eibclient.EIB_MC_SetKey
EIB_MC_SetKey_async = _eibclient.EIB_MC_SetKey_async
EIB_MC_Restart_async = _eibclient.EIB_MC_Restart_async
EIB_MC_Restart = _eibclient.EIB_MC_Restart
EIB_MC_Write_Plain = _eibclient.EIB_MC_Write_Plain
EIB_MC_Write_Plain_async = _eibclient.EIB_MC_Write_Plain_async
EIB_LoadImage = _eibclient.EIB_LoadImage
EIB_LoadImage_async = _eibclient.EIB_LoadImage_async
EIB_Cache_Enable = _eibclient.EIB_Cache_Enable
EIB_Cache_Disable = _eibclient.EIB_Cache_Disable
EIB_Cache_Clear = _eibclient.EIB_Cache_Clear
EIB_Cache_Remove = _eibclient.EIB_Cache_Remove
EIB_Cache_Read_Sync = _eibclient.EIB_Cache_Read_Sync
EIB_Cache_Read = _eibclient.EIB_Cache_Read
EIB_Cache_Enable_async = _eibclient.EIB_Cache_Enable_async
EIB_Cache_Disable_async = _eibclient.EIB_Cache_Disable_async
EIB_Cache_Clear_async = _eibclient.EIB_Cache_Clear_async
EIB_Cache_Remove_async = _eibclient.EIB_Cache_Remove_async
EIB_Cache_Read_Sync_async = _eibclient.EIB_Cache_Read_Sync_async
EIB_Cache_Read_async = _eibclient.EIB_Cache_Read_async


