kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: python:2.7-slim
    commands:
      - pip install --upgrade pip setuptools wheel
      - pip install -e '.[test]'
      - pip install --no-cache-dir mock funcsigs coverage
      - coverage run -m unittest discover -s test/
      - coverage report -m || true

trigger:
  event:
    - push
    - pull_request
